apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: mesh-arena
    app: ai
    version: messi
    vm: unknown
  name: ai-messi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
      version: messi
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        project: mesh-arena
        app: ai
        version: messi
        vm: unknown
    spec:
      containers:
      - image:
        imagePullPolicy: Never
        name: ai
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: TRACING_ENABLED
          value: "0"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_NAME
          value: Messi
        - name: PLAYER_SPEED
          value: "85"
        - name: PLAYER_ACCURACY
          value: "0.95"
        - name: PLAYER_SKILL
          value: "15"
        - name: PLAYER_SHOOT
          value: "300"
        - name: PLAYER_ATTACKING
          value: "90"
        - name: PLAYER_ATT_SHOOT_FAST
          value: "20"
        - name: PLAYER_DEF_SHOOT_FAST
          value: "40"
        - name: PLAYER_COLOR
          value: orange
        - name: JAEGER_SERVICE_NAME
          value: ai.default
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://tracing.istio-system.svc/api/traces
        securityContext:
          privileged: false
