apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ball-dr
  labels:
    app.kubernetes.io/part-of: mesh-arena
spec:
  host: ball
  subsets:
  - name: ball-v1
    labels:
      app.kubernetes.io/version: base
  - name: ball-v2
    labels:
      app.kubernetes.io/version: burst
