# Scenario 2: By label
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ball-vs
  labels:
    app.kubernetes.io/part-of: mesh-arena
spec:
  hosts:
  - ball
  http:
  - match:
    - sourceLabels:
        app.kubernetes.io/version: locals
    route:
    - destination:
        host: ball
        subset: ball-v1
  - match:
    - sourceLabels:
        app.kubernetes.io/version: visitors
    route:
      - destination:
          host: ball
          subset: ball-v1
  - route:
    - destination:
        host: ball
        subset: ball-v2
